### ISSUE TITLE
【番外編】POSTMANを使って郵便番号APIのレスポンスJSONをみてみる

### ISSUE THREAD

**Issue by king-kazu39** [iroha-168/SamplePhoneBook#10]
## 概要
郵便番号APIにリクエストを送りレスポンスを見てみる

[郵便番号API仕様書-公式-](http://zipcloud.ibsnet.co.jp/doc/api)

## 注意
POSTMANを事前にインストールしましょう
[Postman概要/インストール/使用方法](https://meetup-jp.toast.com/818)

## 確認事項
- [x] 必須パラメータと任意パラメータを確認する
- [x] 実在する郵便番号でリクエストしてみる
- [x] 実在しない郵便番号でリクエストしてみる
- [x] 必須パラメータを付けずにリクエストしてみる

**Comment by iroha-168** [comment]
必須パラメータ：zipcode
任意パラメータ：limit, callback

実在する郵便番号でリクエスト->データを取得できる
<img width="500" alt="スクリーンショット 2021-03-28 12 47 11" src="https://user-images.githubusercontent.com/67794229/112741817-c3204a00-8fc3-11eb-8822-b357f5354332.png">

実在しない郵便番号でリクエスト->200台のエラーが出る
<img width="500" alt="スクリーンショット 2021-03-28 12 49 13" src="https://user-images.githubusercontent.com/67794229/112741850-07134f00-8fc4-11eb-981b-1ceff6c17805.png">

必須パラメータなしのリクエスト->400台のエラーが出る
<img width="500" alt="スクリーンショット 2021-03-28 12 50 55" src="https://user-images.githubusercontent.com/67794229/112741874-43df4600-8fc4-11eb-935d-cbf56d52f578.png">

**Comment by king-kazu39** [comment]
郵便番号が複数件取れる場合も試してみてください。

**Comment by king-kazu39** [comment]
英数字や記号をパラメータに含めるとどんなレスポンスが返ってくるか確認してみましょう

**Comment by iroha-168** [comment]
> 郵便番号が複数件取れる場合も試してみてください。

こんな感じでしょうか？わかりにくいですが、同じ郵便番号で複数件データが存在する場合で3件に絞って取得しています
<img width="500" alt="スクリーンショット 2021-03-28 18 39 29" src="https://user-images.githubusercontent.com/67794229/112748184-2080bf00-8ff5-11eb-94a8-1db42360bbf6.png">

**Comment by king-kazu39** [comment]
郵便番号桁数を超えた文字列をリクエストパラメータとして送るとどんなレスポンス結果になるかみてみましょう

**Comment by iroha-168** [comment]
> 郵便番号桁数を超えた文字列をリクエストパラメータとして送るとどんなレスポンス結果になるかみてみましょう

"message": "パラメータ「郵便番号」の桁数が不正です。",
	"results": null,
	"status": 400

が表示されます

**Comment by king-kazu39** [comment]
またAPIのレスポンス結果をまとめてみてください。（表にするなど）
このissueのゴールはどんなリクエストを送ると、どんなレスポンス結果になるかを把握することです。

**Comment by king-kazu39** [comment]
コメント早w
仕事早すぎやわw

**Comment by iroha-168** [comment]
> 英数字や記号をパラメータに含めるとどんなレスポンスが返ってくるか確認してみましょう

こういう風にやってみたのですが、確かめるべきこととしてやり方は適切でしょうか？？
<img width="500" alt="スクリーンショット 2021-03-28 18 44 41" src="https://user-images.githubusercontent.com/67794229/112748318-da782b00-8ff5-11eb-8b2c-248990feaf84.png">

**Comment by king-kazu39** [comment]
> > 英数字や記号をパラメータに含めるとどんなレスポンスが返ってくるか確認してみましょう
> 
> こういう風にやってみたのですが、確かめるべきこととしてやり方は適切でしょうか？？
> <img alt="スクリーンショット 2021-03-28 18 44 41" width="500" src="https://user-images.githubusercontent.com/67794229/112748318-da782b00-8ff5-11eb-8b2c-248990feaf84.png">

バッチグー👍

**Comment by iroha-168** [comment]
「どんなリクエストを送ると、どんなレスポンス結果になるか」をまとめてみました！

実在する郵便番号       ->   status: 200 / データが返ってくる
実在しない郵便番号    ->   status: 400 / null / null
必須パラメータなし    ->   status: 400 / null / 必須パラメータが指定されていません
英数字や記号あり       ->   status: 400 / null / パラメータ「郵便番号」の桁数が不正です
桁数が超えた郵便番号 ->　status: 400 / null / パラメータ「郵便番号」の桁数が不正

**Comment by king-kazu39** [comment]
お、いいねいいね！
例も書いておいた方が後々いいかな。
あと実在する郵便番号(複数件取得の場合)も書いた方がいいかな。
レスポンスがちょっとでも異なるのはできるだけ把握しておきたいからね。

箇条書きでもいいけどマークダウンで表もできるから表にした方がいいんじゃない？
これを参考にAPIクラス作っていくから自分が後で振り返ってわかるように書いた方がいいと思うよ。

例)
|検証内容|リクエスト例  (zipcodeの入力値)|レスポンス内容|備考|
|---|---|---|---|
|実在する郵便番号|4680074| `{status: 200,    message:null,    result: [address1: 愛知県, address2: 昭和区, address3: 阿由知通り]}`| 住所1件分取得|

**Comment by iroha-168** [comment]
| 検証内容 | zipcodeの入力値 |レスポンス内容 | 
----|----|----|
| 実在する郵便番号 | 7830060 | status: 200, message: , result: ["address1": "高知県","address2": "南国市","address3": "蛍が丘"]
| 複数件データが存在する郵便番号 | zipcode=4410302&limit=2 | status: 200, result: ["address1": "愛知県","address2": "豊川市","address3": "御津町下佐脇"],[...] , message: null
| 実在しない郵便番号 | 5555555 | , status: 200, message: null, results: null
| 必須パラメータなし |  | status: 400, message: 必須パラメータが指定されていません, result: null
| 英数字や記号が混入  | hello555#  | status: 400, message: パラメータ「郵便番号」の桁数が不正です, result: null
| 桁数が超えた郵便番号 | 555555555 | status: 400, massage: パラメータ「郵便番号」の桁数が不正, result: null
